# Generated by Django 3.0.6 on 2020-07-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_text', models.CharField(max_length=150)),
                ('num_tweets', models.IntegerField(default=50)),
                ('from_date', models.CharField(default='2020-05-01', max_length=10)),
                ('language', models.CharField(default='en', max_length=2)),
            ],
        ),
    ]
